baseURL = "/"
disqusShortname = ""
languageCode = "fr-fr"
paginate = 10
summaryLength = "20"
#theme = "hugo-future"
title = "Les apprentis marketeux"
url = "https://lesapprentismarketeux.netlify.app/"